### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by aberba** [seanmavley/unifi-voucher-payment-server#1]
I watched your video and it watch very helpful. The info you provided has been valuable as the docs on hubtel was a bit confusing (on the transaction flow) at first. After reading more on the Vodafone cash integration, I noticed using it is not much of a problem (I just need an extract text input for transaction code generated for payment). 

The UX for the delay in response is my current challenge. I'm thinking through. 

I'm working on a nodejs API and I'm trying to their other services for my projects and as open source. Will get back to you. Thanks.

**Comment by seanmavley** [comment]
Hi @aberba . I'm glad you find the video useful. 

About the UX delay in response to the API responses, you've seen one way I'm doing mine using Angular?

https://github.com/seanmavley/unifi-voucher-payment-frontend

You can see it in action at [Enjoy WiFi, Today](https://buy.enjoywifi.today)

**Comment by aberba** [comment]
The API is now live at https://www.npmjs.com/package/hubtel-mx

**Comment by seanmavley** [comment]
Nice work. 
Lemme know when it is ready to be used in production.

**Comment by aberba** [comment]
You changed to using mazzuma now.  Why (technical)? At what Tradeoff?

**Comment by seanmavley** [comment]
@aberba With mazzuma, I make a request, I get a success or failure response. I don't do any callback work. check the code. Saved close to 100 lines of code if not more, just by that switch.

This is LITERALLY ALL I had to do with Mazzuma: 

https://github.com/seanmavley/unifi-voucher-payment-server/blob/master/routes/index.js#L112

You seem to not have seen this: https://blog.khophi.co/instead-excuses-mazzuma-just-does-it/

Of course Hubtel don't give a sh**t what will make lone developers like us enjoy using their APIs, so I guess it is even easier for you guys to conveniently [make fun of us and tease](https://twitter.com/nkansahrexford/status/934545848054308864?s=17). Kudos

**Comment by aberba** [comment]
Ok. Thanks

**Comment by aberba** [comment]
I'm really upset with you. I went through hoops to do hubtel callback with pains only to realize Mazzuma does it in one go. I'm gonna cry :(
